version: '3'
services:
  influxdb:
    image: "influxdb"
    restart: always
    volumes:
      - influxdata:/var/lib/inflxudb
    ports:
      - "8086:8086"
  grafana:
    restart: always
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
    links:
      - influxdb
    build:
      context: .
      dockerfile: Dockerfile-grafana
volumes:
  influxdata:
  grafanadata:
