# list of datasources to insert/update depending 
# whats available in the datbase
datasources:
    # <string, required> name of the datasource. Required
  - name: Influxdb-example
    # <string, required> datasource type. Required
    type: influxdb
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <int> org id. will default to org_id 1 if not specified
    org_id: 1
    # <string, required> url
    url: http://influxdb:8086
    # <string> database name, if used
    database: telegraf
    # <bool> mark as default datasource. Max one per org
    is_default: true
    # <int> including this value garantees that instance with old configs cannot
    #       overwrite your last change.
    version: 1
